<?php
/**
 * Options
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Paylink API
 *
 * API for creating payments with CityPay's Paylink system.
 *
 * OpenAPI spec version: 3.1
 * Contact: support@citypay.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.2
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * Options Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Options
{
    /**
     * Possible values of this enum
     */
    const BYPASS_AVS_POSTCODE = 'BYPASS_AVS_POSTCODE';
    const BYPASS_AVS_ADDRESS = 'BYPASS_AVS_ADDRESS';
    const BYPASS_CSC_REQUIRED = 'BYPASS_CSC_Required';
    const BYPASS_3_DSECURE = 'BYPASS_3DSECURE';
    const BYPASS_CUSTOMER_EMAIL = 'BYPASS_CUSTOMER_EMAIL';
    const BYPASS_CUSTOMER_SMS = 'BYPASS_CUSTOMER_SMS';
    const BYPASS_DUPLICATE_CHECK = 'BYPASS_DUPLICATE_CHECK';
    const BYPASS_MERCHANT_EMAIL = 'BYPASS_MERCHANT_EMAIL';
    const BYPASS_PREAUTH = 'BYPASS_PREAUTH';
    const CREATE_CAC_ACCOUNT_ON_AUTHORISATION = 'CREATE_CAC_ACCOUNT_ON_AUTHORISATION';
    const ENFORCE_AVS_ADDRESS = 'ENFORCE_AVS_ADDRESS';
    const ENFORCE_AVS_POSTCODE = 'ENFORCE_AVS_POSTCODE';
    const ENFORCE_CSC_REQUIRED = 'ENFORCE_CSC_Required';
    const ENFORCE_PREAUTH = 'ENFORCE_PREAUTH';
    const REQUIRE_CUSTOMER_EMAIL = 'REQUIRE_CUSTOMER_EMAIL';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::BYPASS_AVS_POSTCODE,
            self::BYPASS_AVS_ADDRESS,
            self::BYPASS_CSC_REQUIRED,
            self::BYPASS_3_DSECURE,
            self::BYPASS_CUSTOMER_EMAIL,
            self::BYPASS_CUSTOMER_SMS,
            self::BYPASS_DUPLICATE_CHECK,
            self::BYPASS_MERCHANT_EMAIL,
            self::BYPASS_PREAUTH,
            self::CREATE_CAC_ACCOUNT_ON_AUTHORISATION,
            self::ENFORCE_AVS_ADDRESS,
            self::ENFORCE_AVS_POSTCODE,
            self::ENFORCE_CSC_REQUIRED,
            self::ENFORCE_PREAUTH,
            self::REQUIRE_CUSTOMER_EMAIL,
        ];
    }
}


