<?php
/**
 * ConfigTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Paylink API
 *
 * API for creating payments with CityPay's Paylink system.
 *
 * OpenAPI spec version: 3.1
 * Contact: support@citypay.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.2
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ConfigTest Class Doc Comment
 *
 * @category    Class
 * @description Config
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ConfigTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Config"
     */
    public function testConfig()
    {
    }

    /**
     * Test attribute "acs_mode"
     */
    public function testPropertyAcsMode()
    {
    }

    /**
     * Test attribute "custom_params"
     */
    public function testPropertyCustomParams()
    {
    }

    /**
     * Test attribute "expire_in"
     */
    public function testPropertyExpireIn()
    {
    }

    /**
     * Test attribute "merch_branding"
     */
    public function testPropertyMerchBranding()
    {
    }

    /**
     * Test attribute "merch_logo"
     */
    public function testPropertyMerchLogo()
    {
    }

    /**
     * Test attribute "merch_terms"
     */
    public function testPropertyMerchTerms()
    {
    }

    /**
     * Test attribute "lock_params"
     */
    public function testPropertyLockParams()
    {
    }

    /**
     * Test attribute "options"
     */
    public function testPropertyOptions()
    {
    }

    /**
     * Test attribute "postback"
     */
    public function testPropertyPostback()
    {
    }

    /**
     * Test attribute "postback_policy"
     */
    public function testPropertyPostbackPolicy()
    {
    }

    /**
     * Test attribute "redirect_delay"
     */
    public function testPropertyRedirectDelay()
    {
    }

    /**
     * Test attribute "redirect_success"
     */
    public function testPropertyRedirectSuccess()
    {
    }

    /**
     * Test attribute "redirect_failure"
     */
    public function testPropertyRedirectFailure()
    {
    }

    /**
     * Test attribute "return_params"
     */
    public function testPropertyReturnParams()
    {
    }

    /**
     * Test attribute "renderer"
     */
    public function testPropertyRenderer()
    {
    }
}
